//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure." +
                            "Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 A physical hardware device. 的當地語系化字串。
        /// </summary>
        internal static string CustomDeviceDescription {
            get {
                return ResourceManager.GetString("CustomDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://azure.microsoft.com/documentation/articles/iot-suite-connecting-devices/ 的當地語系化字串。
        /// </summary>
        internal static string CustomDeviceInstructionsUrl {
            get {
                return ResourceManager.GetString("CustomDeviceInstructionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Custom Device 的當地語系化字串。
        /// </summary>
        internal static string CustomDeviceName {
            get {
                return ResourceManager.GetString("CustomDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device {0} is already registered. 的當地語系化字串。
        /// </summary>
        internal static string DeviceAlreadyRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceAlreadyRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device {0} is not registered. 的當地語系化字串。
        /// </summary>
        internal static string DeviceNotRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceNotRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There was an error while registering device {0}. 的當地語系化字串。
        /// </summary>
        internal static string DeviceRegistrationExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceRegistrationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The Enabled State must be set. Please select Enabled or Disabled. 的當地語系化字串。
        /// </summary>
        internal static string EnabledStateNotSetError {
            get {
                return ResourceManager.GetString("EnabledStateNotSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Software to simulate a device. Easily extensible for arbitrary events and commands; can run in a Windows Azure worker role. To create a simulated device, please follow the cooler sample instructions. 的當地語系化字串。
        /// </summary>
        internal static string SimulatedDeviceDescription {
            get {
                return ResourceManager.GetString("SimulatedDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Simulated Device 的當地語系化字串。
        /// </summary>
        internal static string SimulatedDeviceName {
            get {
                return ResourceManager.GetString("SimulatedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 An unexpected error occurred. 的當地語系化字串。
        /// </summary>
        internal static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device {0} does not support the command {1}. 的當地語系化字串。
        /// </summary>
        internal static string UnsupportedCommandExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedCommandExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Device already exists in the device registry 的當地語系化字串。
        /// </summary>
        internal static string ValidationDeviceExists {
            get {
                return ResourceManager.GetString("ValidationDeviceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DeviceID cannot be empty or null 的當地語系化字串。
        /// </summary>
        internal static string ValidationDeviceIdMissing {
            get {
                return ResourceManager.GetString("ValidationDeviceIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 One or more validation errors occured for device {0}. 的當地語系化字串。
        /// </summary>
        internal static string ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionMessage", resourceCulture);
            }
        }
    }
}
